
sudo: required
# https://docs.travis-ci.com/user/trusty-ci-environment/
dist: xenial
language: python
python:
  - "3.6"
env:
  - DB=postgres
addons:
    # postgres versions provided by el7 RHSCL (lowest supportable version)
    postgresql: "9.6"
services:
    - postgresql
    - redis-server
before_install:
- sudo add-apt-repository -y ppa:projectatomic/ppa
- sudo apt-get update -qq
- sudo apt-get install -qq -y software-properties-common podman
- sudo mkdir -p /etc/containers
- echo -e "[registries.search]\nregistries = ['docker.io', 'quay.io']" | sudo tee /etc/containers/registries.conf
install: source .travis/install.sh
before_script: source .travis/before_script.sh
script: source .travis/script.sh
after_failure:
  - sh -c "cat ~/django_runserver.log"
  - sh -c "cat ~/resource_manager.log"
  - sh -c "cat ~/reserved_workers-1.log"
