# Ansible playbook to start the pulp service container and its supporting services
---
- hosts: localhost
  gather_facts: false
  vars_files:
    - vars/main.yaml
  tasks:
    - name: "Create Settings Directories"
      file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - settings

    - name: "Generate Pulp Settings"
      template:
        src: settings.py.j2
        dest: settings/settings.py

    - name: "Setup docker networking"
      docker_network:
        name: pulp_ci_bridge

    - name: "Start Service Containers"
      docker_container:
        name: "{{ item.name }}"
        image: "{{ item.image }}"
        auto_remove: true
        recreate: true
        privileged: false
        networks:
          - name: pulp_ci_bridge
            aliases: "{{ item.name }}"
        volumes: "{{ item.volumes | default(omit) }}"
        env: "{{ item.env | default(omit) }}"
        command: "{{ item.command | default(omit) }}"
        state: started
      loop: "{{ services | default([]) }}"

    - name: "Retrieve Docker Network Info"
      docker_network_info:
        name: pulp_ci_bridge
      register: pulp_ci_bridge_info

    - name: "Update /etc/hosts"
      lineinfile:
        path: /etc/hosts
        regexp: "\\s{{ item.value.Name }}\\s*$"
        line: "{{ item.value.IPv4Address | ipaddr('address') }}\t{{ item.value.Name }}"
      loop: "{{ pulp_ci_bridge_info.network.Containers | dict2items }}"
      become: true

    - block:
        - name: "Wait for Pulp"
          uri:
            url: "http://pulp/pulp/api/v3/status/"
            follow_redirects: none
          register: result
          until: result.status == 200
          retries: 20
          delay: 5
      rescue:
        - name: "Output pulp container log"
          command: "docker logs pulp"
          failed_when: true

    - name: "Set pulp password in .netrc"
      copy:
        dest: "~/.netrc"
        content: |
          machine pulp
          login admin
          password password

- hosts: pulp
  gather_facts: false
  tasks:
    - name: "Set pulp admin password"
      command:
        cmd: "pulpcore-manager reset-admin-password --password password"
...
